apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-db-creds
spec:
  provider: vault
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: dbUsername
          key: username
        - objectName: dbPassword
          key: password
  parameters:
    roleName: 'sql-role'
    vaultAddress: 'http://vault.default:8200'
    objects: |
      - objectName: "dbUsername"
        secretPath: "database/creds/sql-role"
        secretKey: "username"
      - objectName: "dbPassword"
        secretPath: "database/creds/sql-role"
        secretKey: "password"
