apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: minio-keys
spec:
  provider: vault
  secretObjects:
    - secretName: minio-secrets
      type: Opaque
      data:
        - objectName: accessKeyId
          key: accessKeyId
        - objectName: secretAccessKey
          key: secretAccessKey
  parameters:
    roleName: 'minio-role'
    vaultAddress: 'http://vault.hashcorp:8200'
    objects: |
      - objectName: "accessKeyId"
        secretPath: "minio/keys/minio-role"
        secretKey: "accessKeyId"
      - objectName: "secretAccessKey"
        secretPath: "minio/keys/minio-role"
        secretKey: "secretAccessKey"
